import type { Metadata } from 'next'
import { Inconsolata } from 'next/font/google'
import './globals.css'
import ChatBubble from './_components/ChatBubble'

const inter = Inconsolata({ subsets: ['latin'] })
// Raleway
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
           <ChatBubble />
      </body>
    </html>
  )
}
